### ISSUE TITLE
Parameter time_to_live do it for hours, days, etc..

### ISSUE THREAD

**Issue by zuenko** [iamsinghrajat/async-cache#11]
https://github.com/iamsinghrajat/async-cache/blob/20a9fdafc746778dd853b55351fa5dc5e28ef6ae/cache/async_ttl.py#L34
https://github.com/iamsinghrajat/async-cache/blob/20a9fdafc746778dd853b55351fa5dc5e28ef6ae/cache/async_ttl.py#L11
It is better to pass the exact parameter for 

`@AsyncTTL(hours=1, seconds=1, days=0, milliseconds=0, ... etc. , maxsize=1024)`

```
datetime.timedelta(
    days=days,
    seconds=seconds,
    microseconds=microseconds,
    milliseconds=milliseconds,
    minutes=minutes,
    hours=hours,
    weeks=weeks
)
```

**Comment by iamsinghrajat** [comment]
@zuenko @inktrap We can easily pass `time_to_live` argument in seconds, datetime library will automatically convert it into microseconds or days accordingly. Passing `hours`,`minutes`, `seconds` or datetime object as argument separately make things  complex. 
```
>> datetime.timedelta(seconds=0.05)
datetime.timedelta(microseconds=50000)
```
```
>> datetime.timedelta(seconds=5000000)
datetime.timedelta(days=57, seconds=75200)
```

**Comment by inktrap** [comment]
Yes, of course, this forces you to use datetime objects. Also this follows other formats, like cachetools https://cachetools.readthedocs.io/en/stable/#

If you don't want to do that and keep it in seconds, I would change the docs to use timedelta beforehand, because it is much clearer and easier to write day=1 instead of writing something like 60*60*24. That's what timedelta is for.

But then I'll see no point in keeping this open and implementing hours, days, minutes, as params because it just duplicates timedelta.
